### PR TITLE
update: pt_BR i18n translation

### PR DESCRIPTION
**Pull request by manuelzzz**
- Translation correction
- Runned `dart run slang apply --locale=pt-BR`

### CODE REVIEW

**Comment by Tienisto** [comment]
Please do not delete the missing translations file

**Comment by manuelzzz** [comment]
It was automatically deleted after i run the the slang command

**Comment by Tienisto** [comment]
Hi, can you please create a new PR and only update the json files without running anything?

**Comment by manuelzzz** [comment]
Okay. I will do that.

**Pull request closed without merging**
