### PR TITLE
Show Transfer Speed (Feature Request: #1608)

### PR DESCRIPTION
**Pull request by KISHORE-KUMAR-S**
Following Feature Request: #1608 

The transfer speed is now visible by default while sending or receiving the file irrespective of languages.

WhatsApp Image 2024-10-21 at 15 16 43
WhatsApp Image 2024-10-21 at 15 12 24
WhatsApp Image 2024-10-21 at 15 12 15

### CODE REVIEW

**Comment by Tienisto** [comment]
Besides the massive PR size, I don't think this should be permanent visible.

**Comment by KISHORE-KUMAR-S** [comment]
> Besides the massive PR size, I don't think this should be permanent visible.

I can't have a CI/CD clearance for format. Is it due to massive pull request?

**Comment by KISHORE-KUMAR-S** [comment]
> Besides the massive PR size, I don't think this should be permanent visible.

I would like to confirm that this should be optional?

**Comment by KISHORE-KUMAR-S** [comment]
> Besides the massive PR size, I don't think this should be permanent visible.

Besides running "dart format ." command, I've formated all the files. This resulted a massive PR size.

**Comment by KISHORE-KUMAR-S** [comment]
> Besides the massive PR size, I don't think this should be permanent visible.

I've formatted all the files, but the PR size is still pretty big after running 'dart format .'. It looks like the CI/CD format check isn't working. Fast transfer speeds are really important for a good user experience and real-time collaboration.

**Comment by Tienisto** [comment]
The speed is important to "nerds" like us. Most users only need to know how long to wait. I also dislike the fact that there are 2 information in brackets now and the higher probability that we need to use 2 lines instead of 1 - both are making the UI worse.

**Pull request closed without merging**
