### PR TITLE
update dependency

### PR DESCRIPTION
**Pull request by Malus-risus**

### CODE REVIEW

**Comment by Tienisto** [comment]
Thank you. However, there is this weird bug #999 
That's why in v1.13.1, I downgraded Flutter 3.16 to 3.13.
Maybe this issue is resolved in the latest hotfix v3.16.9 but this has not been tested yet.

So I would first upgrade to 3.16.9 to see if the issue has been resolved. If not, then 3.13 will likely be used in the next release until Windows 7/8.1 support is dropped somewhere in the future.

**Comment by Malus-risus** [comment]
> 謝謝。然而，有一個奇怪的 bug #999 這就是為什麼在 v1.13.1 中，我將 Flutter 3.16 降級到 3.13。 也許這個問題在最新的修補程式 v3.16.9 中已解決，但尚未經過測試。
> 
> 所以我會先升級到3.16.9看看問題是否已經解決。如果沒有，那麼 3.13 可能會在下一個版本中使用，直到 Windows 7/8.1 支援在未來某個地方被刪除。

ok，thanks

> Thank you. However, there is this weird bug #999 That's why in v1.13.1, I downgraded Flutter 3.16 to 3.13. Maybe this issue is resolved in the latest hotfix v3.16.9 but this has not been tested yet.
> 
> So I would first upgrade to 3.16.9 to see if the issue has been resolved. If not, then 3.13 will likely be used in the next release until Windows 7/8.1 support is dropped somewhere in the future.

ok，thanks

**Comment by Malus-risus** [comment]
> Thank you. However, there is this weird bug #999 That's why in v1.13.1, I downgraded Flutter 3.16 to 3.13. Maybe this issue is resolved in the latest hotfix v3.16.9 but this has not been tested yet.
> 
> So I would first upgrade to 3.16.9 to see if the issue has been resolved. If not, then 3.13 will likely be used in the next release until Windows 7/8.1 support is dropped somewhere in the future.
so 3.19 flutter has bugs?

**Comment by Tienisto** [comment]
I cannot test this because I don't work with Windows 7 but people at #999 can.

**Comment by Tienisto** [comment]
Sorry, this dependency update is too breaking

**Pull request closed without merging**
