### PR TITLE
refactor: remove platform checks in macos_channel.dart

### PR DESCRIPTION
**Pull request by ShlomoCode**
thoughts?

### CODE REVIEW

**Comment by Tienisto** [comment]
Hi. There are native `assert`s in Dart that might be better. So it doesn't crash in production and only throws during debug mode

**Comment by ShlomoCode** [comment]
But if we call function in wrong case, we'd prefer a crash so we know there's a problem here, over silencing the error, right?

**Comment by ShlomoCode** [comment]
What is meant by abstraction layer?

**Comment by Tienisto** [comment]
Looking at the code again, I think we can remove the checks altogether since it is clear that any function in `macos_channel.dart` should be called on macOS environments only. The function will throw an error regardless of your added exception.

There are already `taskbar_helper.dart` and `autostart_helper.dart` that are platform independent.
However, `pendingFilesStream` and `pendingStringsStream` should be extracted to an extra file also (for example `file_listener.dart` where calls are proxied to `macos_channel.dart` for macOS and are no-op for any other platform.

**Comment by ShlomoCode** [comment]
@Tienisto See now

**Pull request merged**
