### PR TITLE
Linux: Use tray_manager instead of system_tray; remove system_tray

### PR DESCRIPTION
**Pull request by ix5**
Using [tray_manager](https://pub.dev/packages/tray_manager) for Linux as well allows ditching of the unreliable and seemingly less-than-well maintained flutter library [system_tray](https://pub.dev/packages/system_tray) and unifies desktop tray handling across platforms.

At the same time, use upstream `tray_manager` instead of a forked repo (which was stuck on 0.2 and did not contain e.g. leanflutter/tray_manager#38 ). This additionally enables building on Linux again since Tienisto's forked repo used to disable the Linux plugin: Tienisto/tray_manager@b37f5e0. This also works around issues with newer libayatana-appindicator versions: leanflutter/tray_manager#38

Caveats discussed previously still apply: https://github.com/localsend/localsend/pull/404

Mainly:
- Flutter versions installed using `snap` having incompatible `GLib`: https://github.com/leanflutter/tray_manager/issues/30 and https://github.com/leanflutter/tray_manager/issues/28.
  Note that the incompatibility should have existed with both `system_tray` as well as `tray_manager`, the latter being a slightly more maintained fork (?) but utilizing very similar build macros
- Reliance on `libayatana-*` packages

As for @TheGB0077 saying:

> (I tried to make the tray manager work for Linux but it didn't work still)

I'm not quite sure what the issue was, but it seems to work okay now. The only thing to keep note of for me was to guard the call to `setToolTip()` since it would throw a `MissingPluginException` on Linux, but this was noted in the API docs of `tray_manager`.

For reference, potentially relevant prior discussions/commits: 
- https://github.com/localsend/localsend/commit/53b1899aec3ab2e74681c908274c8dd7e387e99d
- https://github.com/localsend/localsend/issues/409
- https://github.com/localsend/localsend/issues/651

### Issues?

I have only tested this on an up-to-date Arch Linux system and cannot speak to the viability of `tray_manager` for other (older) distros.

It seems that the `AppImage` and `Flatpak` distributors as well as Debian-based systems _might_ not be fully compatible with _anything_ recent, but I cannot see how re-enabling `tray_manager` on Linux would surface any additional errors that weren't previously being thrown by `system_tray`.

My setup:
```
libappindicator-gtk3 12.10.0.r298-3
libayatana-appindicator 0.5.93-1
libayatana-indicator 0.9.4-1
libcanberra 1:0.30+r2+gc0620e4-3
```
With `flutter` installed through `fvm`:
```
$ fvm flutter --version
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (5 months ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
```

### CODE REVIEW

**Comment by ix5** [comment]
@Nixuge I see your efforts at packaging for the AUR. With this PR (for me locally) I can successfully use LocalSend with a tray icon again.

Note however that this is using the generated artifacts (`flutter build linux --release`) for packaging using a `PKGBUILD` and not extracting anything from the debian tarballs.

See https://github.com/localsend/localsend/issues/40

**Comment by Tienisto** [comment]
Thanks for your effort! I will test this ASAP

**Comment by ix5** [comment]
Splendid, thank you @Tienisto! You've created and maintained a great app, I'm happy to contribute.

Pushed with a fix for the CI complaining about unused imports (it was `dart:io` that I missed because I didn't realize `exit(0)` belonged to that lib... sorry, first time using `flutter`/`dart`)

**Comment by Tienisto** [comment]
LGTM!

**Comment by Nixuge** [comment]
Finally here, will try and switch the -bin package to use the deb/targz see if it works

**Comment by Nixuge** [comment]
> Note however that this is using the generated artifacts
Those seem to work just fine anyways (see the -git AUR package) unlike what's provided in the releases tab for some reason (no idea how you're making those @Tienisto?)

Anyways if you got rid of that dependency it's probably fixed anyways, thanks for the epic PR.

Got a PKGBUILD for deb support ready for when this gets into a release build

**Comment by Tienisto** [comment]
The release binaries are all built on the Github Pipeline:

https://github.com/localsend/localsend/blob/main/.github%2Fworkflows%2Frelease.yml

@Nixuge

**Comment by Nixuge** [comment]
Aight thanks, did a [test build](https://github.com/Nixuge/localsend/actions/runs/8852570643) and it seems to work perfectly now with the deb

image

**Pull request merged**
