### PR TITLE
ci: bump Winget Releaser to v2 & add dependabot

### PR DESCRIPTION
**Pull request by sitiom**
v2 fixes a critical error in the action: https://github.com/vedantmgoyal2009/winget-releaser/issues/84

Additionally, add Dependabot to bump dependencies automatically.

### CODE REVIEW

**Comment by sitiom** [comment]
https://github.com/localsend/localsend/actions/runs/4162196977/jobs/7201073736

@Tienisto Why is v1 still used in this run?

**Comment by Tienisto** [comment]
Because the release tag was 2 days ago. Let's hope that everything works, if not, then I need to cherry pick your commit for `v1.7.0`

**Comment by Tienisto** [comment]
It seems that the bot tries to form it to my personal accout:

```text
Fork of winget-pkgs not found. Forking...
Forked winget-pkgs repository: Tienisto/winget-pkgs
```

**Comment by sitiom** [comment]
- Opened up an issue upstream: https://github.com/vedantmgoyal2009/winget-releaser/issues/100

**Comment by sitiom** [comment]
> It seems that the bot tries to fork it to my personal accout:
> 
> ```
> Fork of winget-pkgs not found. Forking...
> Forked winget-pkgs repository: Tienisto/winget-pkgs
> ```

Meanwhile, please try rerunning the same job to create the PR. Thanks!

**Pull request merged**
