### PR TITLE
Overall Project Improvements

### PR DESCRIPTION
**Pull request by beholdenkey**
Hey, Great Application, by the way; very simple and clean.

- Formatting fixes, spacing, syntax, structure
- Overhauled msix_downloader script (Let me know your thoughts)
- Updated Project README document
- Created Contributing Document.

### CODE REVIEW

**Comment by Tienisto** [comment]
Thanks for your contribution! How come that the images use less space?

**Comment by beholdenkey** [comment]
So one of the tools I use is called [oxipng](https://github.com/shssoichiro/oxipng) which functions as a lossless compression optimizer. Great when working with a lot of assets.

**Comment by Tienisto** [comment]
Unfortunately, I couldn't get your new msix downloader running:

It says "Could not verify the variable because the value C:\Users\<user>\AppData\Local\Temp\9NCB4Z0TZ6RR is not valid for the SavePathRoot variable."

Original (in German though):

```text
PS C:\Users\<user>\Work\localsend\scripts\msix> .\msix_downloader.ps1 -StoreURL https://www.microsoft.com/store/productId/9NCB4Z0TZ6RR
C:\Users\<user>\Work\localsend\scripts\msix\msix_downloader.ps1 : Die Variable kann nicht überprüft werden, da der Wert
C:\Users\<user>\AppData\Local\Temp\9NCB4Z0TZ6RR kein gültiger Wert für die SavePathRoot-Variable ist.
In Zeile:1 Zeichen:1
+ .\msix_downloader.ps1 -StoreURL https://www.microsoft.com/store/produ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,msix_downloader.ps1
```

**Comment by beholdenkey** [comment]
@Tienisto I had a workaround, but I don't think it makes more sense than the original, so I reverted to the original script. Let me know if you see any other issues.

**Comment by Tienisto** [comment]
LGTM. Thanks!

**Pull request merged**
