### PR TITLE
feature: Added auto-closing dialog 

### PR DESCRIPTION
**Pull request by hkhatuwal**
feat: Add auto-closing dialog for received files (excluding gallery files)

- Implemented a dialog that opens when a received file (not saved in the gallery) is received.
- Added a close button that automatically triggers after a set period of inactivity, in case the user doesn't interact.
Screenshot_2024-10-20-13-43-23-38_0eb0bf3377316423b280100c521cf1b9

### CODE REVIEW

**Comment by hkhatuwal** [comment]
Hi, I am sorry but i tried to do all but after doing `dart format --line-length 150 lib test` it automatically make the files changed and they are counted as changed file . i am not sure whats the issue. can anyone please help on this matter.

**Comment by hkhatuwal** [comment]
I ran `flutter pub run slang` prior to executing dart format, but after running dart format, the file still shows as modified and is marked as changed in Git.

**Comment by Tienisto** [comment]
It's the other way around: first format, then run slang

**Comment by hkhatuwal** [comment]
> It's the other way around: first format, then run slang

Ok, I did that and it worked. Thanks

**Comment by Tienisto** [comment]
Thanks

**Pull request merged**
