### PR TITLE
add duplicate files validation when pick image or files or directory

### PR DESCRIPTION
**Pull request by programmermager**
linked to #903 

I try to add validation for already selected files from menu options file, media or folder.

# Before 
### MacOs
https://github.com/localsend/localsend/assets/7869219/843a0615-a9de-4d90-9c89-6ebc39572872

### Android
https://github.com/localsend/localsend/assets/7869219/7ef7ccd1-b6e3-4ec7-8794-b790eb104439

# After 
### MacOs
https://github.com/localsend/localsend/assets/7869219/1c17290e-a86c-44a0-bcf3-1c81348727fd

### Android
https://github.com/localsend/localsend/assets/7869219/ec4923ee-7900-4834-a5f4-0e9bf3687755

### CODE REVIEW

**Comment by Tienisto** [comment]
Thank you. I think we need to check the absolute path and not the base path since users can add a directory (with its sub directories). There might be the case that you have 2 files of the same name but in different directories

**Comment by programmermager** [comment]
> Thank you. I think we need to check the absolute path and not the base path since users can add a directory (with its sub directories). There might be the case where you have 2 files with the same name but in different directories

i see, the reason why i use the basename because the path from gallery and file is different although the file is same but it returns different path.

let me think the more effective way

**Comment by programmermager** [comment]
@Tienisto I believe it's not possible to compare using an absolute path when the files come from the file picker and media picker. They are entirely different even if the files are the same. Below, I have attached the paths provided by the file picker and media picker.

pathimage

The green line represents the absolute path from the file picker, while the yellow one is from the media/gallery. It's the same file; the only thing that hasn't changed is the file name.

I would like to suggest continuing to use the basename for validation, but with additional comparison based on file size. Perhaps comparing only the file names could lead to errors, but if we compare based on both the file name and size parameters, I believe it would have high accuracy, unless there is one duplicated file.

WDYT?

**Comment by WubTheGame** [comment]
> @Tienisto I believe it's not possible to compare using an absolute path when the files come from the file picker and media picker. They are entirely different even if the files are the same. Below, I have attached the paths provided by the file picker and media picker.
> 
> pathimage
> The green line represents the absolute path from the file picker, while the yellow one is from the media/gallery. It's the same file; the only thing that hasn't changed is the file name.
> 
> I would like to suggest continuing to use the basename for validation, but with additional comparison based on file size. Perhaps comparing only the file names could lead to errors, but if we compare based on both the file name and size parameters, I believe it would have high accuracy, unless there is one duplicated file.
> 
> WDYT?

Wouldn't comparing based on file hash be better? Perhaps a niche scenario, but you can (accidentally or not) name two unrelated files the same thing and if they manage to be the same size, that'd not be good. Though I guess it could also depend on how precise in terms of bytes the filesize check is (I don't know how those would work). Point is, I think there'd be a more effective way than a filesize check. In fact, a hash check would cover everything else about the file too. If checking for an absolute duplicate, I think you'd want a hash check.

Also wondering, why does Localsend copy files into a temporary directory of its own before sending them? What's the point of that? Why not just collect paths and grab from them at the moment of transfer? I can see that being a problem if you're low on storage.

Not a developer, so please pardon any misunderstandings.

**Comment by programmermager** [comment]
> > @Tienisto I believe it's not possible to compare using an absolute path when the files come from the file picker and media picker. They are entirely different even if the files are the same. Below, I have attached the paths provided by the file picker and media picker.
> > pathimage
> > The green line represents the absolute path from the file picker, while the yellow one is from the media/gallery. It's the same file; the only thing that hasn't changed is the file name.
> > I would like to suggest continuing to use the basename for validation, but with additional comparison based on file size. Perhaps comparing only the file names could lead to errors, but if we compare based on both the file name and size parameters, I believe it would have high accuracy, unless there is one duplicated file.
> > WDYT?
> 
> Wouldn't comparing based on file hash be better? It'd would cover everything else about the file too. If checking for an absolute duplicate, I think that'd be the way to go.
> 
> Also wondering, why does Localsend copy files into a temporary directory of its own before sending them? What's the point of that? Why not just collect paths and grab from them at the moment of transfer? I can see that being a problem if you're low on storage.
> 
> Not a developer, so please pardon any misunderstandings.

I think it's a default in the file picker library used

**Comment by Tienisto** [comment]
I think we should only exclude the same absolute file (when selected from the file picker) for now - which is still an improvement over the current version.

Only comparing the file size would cause false positives in rare cases which essentially a bug.

Calculating the hash would significantly increase the time during file selection (which is already quite slow sometimes).

**Comment by programmermager** [comment]
btw the latest i tried to comparing the basename and file size, not only the size.

Are you saying it's acceptable for the same file to be included in the list of files to be sent when selected from the files and media menu?

**Comment by Tienisto** [comment]
Yeah, comparing file name and file size just feels not right.

Ideally, file name and hash would be better but it's too slow.

To me, only applying the validation to "File" is enough if we use absolute paths.

That's just my opinion. I am open for other opinions.

**Comment by programmermager** [comment]
I tried to perform a comparison using bytes. The problem wasn't particularly noticeable for image files. However, when selecting large files, such as videos and in large quantities, it takes too much time. So that options i believe we both doesnt agree to use that.

So, if you believe that a comparison based on name and size is not effective, it seems like the best option at the moment is an absolute path comparison. The drawback is that if the same file is retrieved using different methods, for example, via files and media, it will still be accepted and added to the list of files sent.

i will push new commit for comparation using absolute path

**Review by Tienisto — APPROVED** [review]

**Comment by Tienisto** [comment]
Thank you. This should be fine for now.

**Comment by programmermager** [comment]
My Pleasure, Hopefully I can contribute more here. 

I have some ideas that might be implemented in LocalSend

**Pull request merged**
