### PR TITLE
Support file/image transfer by pasting files from the clipboard.

### PR DESCRIPTION
**Pull request by gitstart**
fixes https://github.com/localsend/localsend/issues/568
fixes https://github.com/localsend/localsend/issues/210

### PR Description
This PR add feature to send files that are copied to the clipboard 

### Demo video 
https://www.loom.com/share/929b2113cc4a487e9b78781c0e30facd

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by Tienisto** [comment]
Thank you! I will test this out in a few days.

**Comment by Tienisto** [comment]
It works nice!

Do you know if this can be made more general? If I paste text, it does not work.

Thinking about this feature again, I think it would be simpler if a dialog is opened if the Flutter window gets refocused. Like "Do you want to use the clipboard contents? Cancel | Use Clipboard

Let me know if you can do that.

**Comment by gitstart** [comment]
Hi @Tienisto thanks for reviewing PR.

We can try to make pasting text work but  do you think popup a dialog asking if user want to use clipboard content or not is a good user experience? If so then please let us know we will make changes accordingly.

**Comment by Tienisto** [comment]
You are right. I will just merge this until we have a better idea.

**Pull request merged**
