### PR TITLE
ADD: Alert while deleting  history

### PR DESCRIPTION
**Pull request by pantshaswat**
I added a dialog box when the user presses the Delete history button, asking for reconfirmation to delete history. I addressed issue #660. I just coded a box in receive_history_page.dart for now, can also make a widget for reconfirmation.

### CODE REVIEW

**Comment by Tienisto** [comment]
Thanks for your contribution. Since you probably have Flutter installed, you could edit the i18n file (https://github.com/localsend/localsend/blob/main/app/assets/i18n/strings.i18n.json), then after running `dart run slang`, you should have the new translations. Editing the generated file is not good because it will be overridden again

**Comment by pantshaswat** [comment]
I just changed the i18n file and generated the file as you mentioned.

**Comment by WebSnke** [comment]
Hi, I would like to translate the strings that will be added through this pull request. How should I approach that?

**Comment by Tienisto** [comment]
@WebSnke Hi, the easiest way is just to wait until this PR is merged :)

You could also fork this PR (https://github.com/pantshaswat/localsend/tree/fix/660/confirm-delete-history) but there is a risk that something might be changed

**Comment by WebSnke** [comment]
> @WebSnke Hi, the easiest way is just to wait until this PR is merged :)
> 
> You could also fork this PR (https://github.com/pantshaswat/localsend/tree/fix/660/confirm-delete-history) but there is a risk that something might be changed

Ok, thanks.

**Comment by Tienisto** [comment]
Thanks. I refactored the code a little bit to keep the code style consistent

**Pull request merged**
