### PR TITLE
feat(macos): add sandboxed launch at login for App Store version

### PR DESCRIPTION
**Pull request by ShlomoCode**
https://github.com/localsend/localsend/issues/1242

Not used CocoaPods since the owner [says](https://github.com/sindresorhus/LaunchAtLogin-Legacy/releases/tag/v3.0.0#:~:text=It%20didn%27t%20work%20correctly%20anyway.) taht "It didn't work correctly".

ref https://github.com/sindresorhus/LaunchAtLogin-Legacy/issues/33#issuecomment-2253207190, ref https://github.com/hisaac/CenterMouse/blob/main/CenterMouse/Sources/AppDelegate.swift

### CODE REVIEW

**Comment by Tienisto** [comment]
I am thinking to upgrade to the latest Flutter version so that we can use the Swift Package Manager.
I think this would be easier to maintain your recent macos changes

**Comment by ShlomoCode** [comment]
Sounds good!
All that's left here to make it ready to merge is to keep the AutoStartHidden preference for macOS as now it's not determined by the file contents. Is it worth doing it in Flutter or in the macOS Runner? Thoughts?

**Comment by Tienisto** [comment]
I think you can do it in `UserDefaults`. There is not much of a difference though so pick the solution you are comfortable with!

**Comment by ShlomoCode** [comment]
I think it's ready

**Comment by Tienisto** [comment]
Nice, thank you!

**Comment by ShlomoCode** [comment]
@Tienisto I think we need to add deletion of the old agent to prevent duplication for those who already activated the old way?

**Pull request merged**
