### PR TITLE
Web UI styles added and small fixes

### PR DESCRIPTION
**Pull request by TheGB0077**
#### So far only the Teal color has been used from Localsend's color palette, but the page could incorporate more from it. Also, the styles could be split to a separate file, if necessary.

Other Changes: 

```javascript
	// Looking for "Win" can match with Windows, Win64 or Win32. 
	if (userAgent.contains("Windows")) {
    if (userAgent.contains("Win")) {
	
	// iOS userAgent also contains Mac OS, example: 
	// Mozilla/5.0 (iPhone13,2; U; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/15E148 Safari/602.1
    } else if (userAgent.contains("Macintosh") || userAgent.contains("Mac OS")) {
    } else if (userAgent.contains("Macintosh")) {

	// Using "X11" ensures it is a Linux desktop and not a potential variant, like Android.
    } else if (userAgent.contains("Linux")) {
    } else if (userAgent.contains("X11"))

```

### CODE REVIEW

**Comment by Tienisto** [comment]
The text over the teal background seem to be hard to read. Maybe use a lighter teal color?

**Comment by TheGB0077** [comment]
The 2-column separation only shows up on a tablet size view, because if there is only 1, then the row size gets stretched way too much.
On a regular phone there's only 1 column

image

image

And then at the desktop level we have a regular view
image

#### And what about this tone, is it good?

image

**Comment by Tienisto** [comment]
I see. Having the file size as 2nd row still seems to be overkill as there is only one attribute (the size).
Maybe have 4 columns instead so we have:

|File name|size|file name|size
|---|---|---|---|
|file a|123|file b |123

Regarding the color, you can take the 300-500 version of `teal`: https://materialui.co/colors/

**Comment by Tienisto** [comment]
Another solution for tablet is to write the file size in brackets: `myImage.jpeg (3.2 MB)`. So you don't need a second row either.

**Comment by Tienisto** [comment]
You could also add the teal color to the table header, then you don't need to have it in the file size column

**Comment by TheGB0077** [comment]
> Another solution for tablet is to write the file size in brackets: `myImage.jpeg (3.2 MB)`. So you don't need a second row either.

I did with a::after 
image

image


image

**Comment by TheGB0077** [comment]
This is how it looks with Teal 400

image

**Comment by Tienisto** [comment]
Yeah, I am fine with that 👍

**Comment by Tienisto** [comment]
Nice, thanks!

**Pull request merged**
