### PR TITLE
Migrate `image_gallery_saver` to `gal`

### LINKED ISSUE #237: Don`t clear photo metadata
### Is your feature request related to a problem? Please describe.

Localsend clears all metadata from photos

### Describe the solution you'd like

-

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #430: Bug report - iOS devices cannot receive full GIF files
### Describe the bug

Thanks for making this software.

Sending a GIF file on a PC to an iOS device can only display the first frame.

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Sending GIF files of any size and capacity to the iOS device shows that it is successfully completed, but only the first frame of the screen can be displayed.

### Screenshots

_No response_

### Desktop (please complete the following information)

Windows 11 22H2
v1.9.0

### Smartphone (please complete the following information)

iPhone 13mini
16.4.1
v1.9.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by natsuk4ze**
### ⚠️ This is not tested please test by co-authoring. @Tienisto 

This will 
- close #430 
- close #237

### CODE REVIEW

**Comment by Tienisto** [comment]
One question, does it also fix #237 ? This would be great!

**Comment by natsuk4ze** [comment]
> One question, does it also fix #237 ? This would be great!

May be

**Comment by natsuk4ze** [comment]
It should be noted that `gal` does not support the omission of file extensions.
Please see: https://github.com/natsuk4ze/gal/wiki/Formats

**Comment by Tienisto** [comment]
Thank you! Saving GIFs and persisting metadata works now!

**Comment by natsuk4ze** [comment]
np👌

**Pull request merged**
