### PR TITLE
feat(macos): add share extension

### PR DESCRIPTION
**Pull request by ShlomoCode**
Added LocalSend to [macOS Share menu](https://support.apple.com/en-jo/guide/mac-help/mh40614/mac) (currently for files only)

closes https://github.com/localsend/localsend/issues/586

### CODE REVIEW

**Comment by ShlomoCode** [comment]
@Tienisto If you want to help me with the Dart side I can also add support for strings sharing. are you interested?

**Comment by Tienisto** [comment]
Thank you!
It seems to properly select the file. However, I've noticed that the permission is not granted when triggered via "Share".
However, when I drag-and-drop the file into the app / app icon / menubar icon, then the permission is granted and I can send the same file via "Share".

**Comment by ShlomoCode** [comment]
Thanks for catching this! I will investigate it

**Comment by ShlomoCode** [comment]
@Tienisto I pushed a patch, now it should work properly. For technical details and traces of research, please see the comments I added.

Note this comment: [`de35bc8` (#1739)](https://github.com/localsend/localsend/pull/1739/commits/de35bc89a451d3cf5b8382b5bdc3621b2e94dde6#diff-1b28167c9d01216d1e06ec90fdc49e307367adb382d0b0530ad596efa2bc1ae6R28)
I will need you to tell me where the flutter side can send a message to the macos side that the handle to the file is no longer needed, so that we can call `stopAccessingSecurityScopedResource`.

**Comment by Tienisto** [comment]
Thanks! It works! I will merge this and will add the call to stopAccessingSecurityScopedResource later

**Comment by ShlomoCode** [comment]
Great! I want to add support for text sharing as well, can you please give me a small example snippet how do I add a text snippet to the queue from `macos_channel.dart`?

**Comment by Tienisto** [comment]
Similarly to `getPendingFilesStream`, you would need to listen to another stream right at the app start.
For example, you can call `getMessageStream` right below `getPendingFilesStream` (https://github.com/localsend/localsend/blob/main/app/lib/config/init.dart#L198)

```dart
getMessageStream().listen((message) {
        ref.redux(selectedSendingFilesProvider).dispatch(AddMessageAction(message: message));
        ref.redux(homePageControllerProvider).dispatch(ChangeTabAction(HomeTab.send));
      });
```

**Comment by NayamAmarshe** [comment]
Amazing! Thank you for the PR!

**Pull request merged**
