### PR TITLE
[fixed] solved issue Overlapping UI Elements on Windows #1424

### PR DESCRIPTION
**Pull request by CHUNG-HAO**
[fiexed] solved issue Overlapping UI Elements on Windows #1424

### CODE REVIEW

**Comment by CHUNG-HAO** [comment]
https://github.com/localsend/localsend/assets/67829896/ea5f2e33-d2c7-4b57-bffb-feaf7ffb32cc

Effect like it.

**Comment by CHUNG-HAO** [comment]
The original size remains unchanged, and other sizes remain unchanged. The only difference is when the picture is reduced to the smallest size, and conflicts are resolved in this way.

**Comment by CHUNG-HAO** [comment]
thank you for ur approval ! I should continue to solve the github action problem until check OK, haha

**Comment by Tienisto** [comment]
Thank you. A side note: we need to use Flutter 3.13 to support Windows 7 (at least for the next release)

**Pull request merged**
