### PR TITLE
feat: support clipboard for android

### LINKED ISSUE #1753: Feature request: support clipboard for android
### Is your feature request related to a problem? Please describe.

Add clipboard support for android, This can be used as the front of the clipboard sync feature (#163)

### Describe the solution you'd like

Add clipboard button in android app.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Seidko**
### description
Support clipboard for android, add paste button.
close #1753 

This pr need wait upstream to update. It modify lot of dependencies and need more test.

### CODE REVIEW

**Comment by ShlomoCode** [comment]
Are all the dependency updates (for example `win32_registry`) really related to this feature? I'm in favor of separating things, you should update the dependencies in a separate PR so that things are clear and easy to debug

**Comment by Seidko** [comment]
> Are all the dependency updates (for example `win32_registry`) really related to this feature?

Yes I found it was unnecessary to change. I'm tested and found these dependency should be update:
- `pasteboard` necessary updated dependency of this feature 
- `intl` because `flutter_localizations` from sdk which depends on intl 0.19.0
- `uuid` depend by new version of pasteboard
- `wechat_assets_picker` should be update because old `photo_manager` has many build error:
    <details>
    <summary>Screenshot</summary>

    image
   </details>

**Comment by Tienisto** [comment]
Thank you for the PR.
Your PR introduces `pasteboard` dependency that requires Dart 3.4 or later (which means Flutter 3.22 or later).
Currently, the Flutter version is fixed to 3.13 (managed by fvm). The only reason for this is Windows 7 support. Unfortunately, I don't have any analytics to measure the percentage of Windows 7 users but we need to drop Windows 7 support eventually.

We could drop Windows 7 support in the next version

**Comment by Seidko** [comment]
> Currently, the Flutter version is fixed to 3.13 (managed by fvm).

I've tried to rollback `pasteboard` version and cherry-pick my changes at Seidko/flutter-plugins@bca6d5a0a31befe40d6d749a68906242187120b2, What is exciting is that it works! We can fork the `pasteboard` package or drop Windows 7 support.

**Comment by Seidko** [comment]
I tried revert some dependencies and SDK changes at [this branch](https://github.com/Seidko/localsend/tree/fork-pasteboard). I build it and run successfully on windows but I can't build android platform because these `photo_manager` error:
<details>
<summary>Screenshot</summary>

image
</details>
I'm not sure if it cause by my android version. How do I fix it?

**Comment by Tienisto** [comment]
@Seidko do you use Flutter 3.13 (for example via [fvm](https://fvm.app)?) Have you tried to run `flutter clean`?

**Comment by Seidko** [comment]
Oh yes i can build it before i `flutter clean`, Thanks very much!

**Comment by Tienisto** [comment]
Hi, please wait until LocalSend has been updated to latest Flutter version.
I decided this in [#1793](https://github.com/localsend/localsend/pull/1793#issuecomment-2367004886)

**Comment by Seidko** [comment]
Okay, thank you for your work!

**Comment by Tienisto** [comment]
LocalSend now uses Flutter 3.24.3.

**Comment by Seidko** [comment]
I've resolve all the confilct and merge main branch.

**Comment by Tienisto** [comment]
Nice!

**Pull request merged**
