### PR TITLE
Update windows icon

### LINKED ISSUE #627: The default icon color on the desktop need to be optimized?
### Describe the bug

The icon on windows desktop is not clear
image

### To reproduce

by default

### Expected behavior

More clear transparent icon

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tienisto**
Follow-up for #728 

Closes #627

### CODE REVIEW

**Comment by Tienisto** [comment]
Waiting for https://github.com/YehudaKremer/msix/issues/239 to be fixed

**Comment by kra-mo** [comment]
The issue affects Linux too

**Comment by GaryElshaw** [comment]
@Tienisto Is this better?

localsend

**Comment by Tienisto** [comment]
Thanks @GaryElshaw , I will try out your image as soon as I have time!

**Comment by Tienisto** [comment]
Unfortunately, the issue still exists @GaryElshaw

**Comment by GaryElshaw** [comment]
Try, try...

windows-icon-512

**Comment by Tienisto** [comment]
@sergd88 
Let's discuss here to keep the msix issue clean.

Basically there was an issue where the icon is not really visible on Windows.

This would change the launch icon for Windows and will not affect any other places.

**Comment by sergd88** [comment]
> @sergd88 Let's discuss here to keep the msix issue clean.
> 
> Basically there was an issue where the icon is not really visible on Windows.
> 
> This would change the launch icon for Windows and will not affect any other places.

Before version 1.12, I used .msix because there was no .exe package available before. Accordingly, I used the app for many months, and I never encountered the "invisible icon" issue. This is on Windows 11. If you mean that the icon in Windows 10 is very small, as mentioned in [#627](https://github.com/localsend/localsend/issues/627) (shown in the screenshot 1), then yes, that's possible because in Windows 10, the icons of .msix package apps are overlaid on the Windows tile, which was a strange design choice they used back then.

In general, I recommend using an icon with the .ico extension for Windows, as it's native to Windows. Similarly, using .svg is preferable for Linux for better display quality and to minimize various display issues.

As I mentioned earlier regarding Android, the icon with a white circular background looks like a ball. On Android, the icon is of a fairly large size, so it's not critical, but on Windows, it's quite small and doesn't look good (I tried this option, and I'm attaching the corresponding icon). Overall, an icon without a background looks cleaner, in the style of AirDrop. If possible, please try using my .ico icon (I'm attaching it again) that I shared and explained in issue [#826](https://github.com/localsend/localsend/issues/826). I believe it should work without any problems as it already includes icons of various sizes (shown in the screenshot 2).





[localsend-icon.zip](https://github.com/localsend/localsend/files/13252754/localsend-icon.zip)

**Comment by B4undless** [comment]
What do you think about these logos?
local-_fill
localsend
@Tienisto

**Comment by GaryElshaw** [comment]
Sorry @Tienisto, i should have been clearer. @sergd88 is correct by recommending the multiple resolution .ico file being the right approach for Windows icons.

**Pull request merged**
