### PR TITLE
README: Changing the language sequence for all available translations, based on the language order on the website

### PR DESCRIPTION
**Pull request by sergd88**
I've updated the language sequence in all available translations. I added Ukrainian and Russian to the list in other translations, as I wasn't entirely sure if I could change the order, so I initially refrained from making any changes. I used the language list on the website as a reference. I also made minor adjustments to the Ukrainian and Russian translations.

### CODE REVIEW

**Comment by sergd88** [comment]
@Tienisto 
I fixed the paths to the translations that I broke from the very beginning. Since I created the translations based on the main README, I initially forgot to add the root symbol "/" before README.md. And after I opened a pull request to change the language order, I broke everything again because instead of a relative path, I specified an absolute one, without checking how it was implemented in other translations. I sincerely apologize. However, the checks are still somehow failing, possibly because the previously approved pull request had an error and broke everything or perhaps, the syntax in the link name [English (Default)] is somehow considered problematic, although it doesn't seem to contradict the Markdown syntax itself 🤷‍♂️

**Comment by sergd88** [comment]
Also, I'd like to take this opportunity to wish you a Happy New Year 🎄
May it be filled with positivity, bright colors, and joyful events. Wishing you excellent health, great mood, happiness, creative ups, prosperity and peace 🎉

**Comment by Tienisto** [comment]
Thank you! I wish you happy new year also! 🎉

**Comment by saurabh12453** [comment]
Compiled #2179, Can u please give me a call? Please send accurate reports
to cross verify. Can u please check which light is blinking in software
tester department so i can assign engineer Mr Mohit to resolve the issue as
soon as possible. This is to be closed by the end of the day today.

**Comment by saurabh12453** [comment]
Happy New Year Team

**Pull request merged**
